# Generated by Django 2.2.5 on 2019-09-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('article_number', models.IntegerField()),
                ('cost_per_unit', models.FloatField(default=1)),
                ('unit_name', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('cl', 'cl'), ('l', 'l')], default='kg', max_length=100)),
                ('unit_amount', models.FloatField(default=1)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='ingredients/')),
                ('category', models.CharField(choices=[('Diary', 'Diary'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Backing & GRains', 'Backing & GRains'), ('Added Sweeteners', 'Added Sweeteners'), ('Spices', 'Spices'), ('Meats', 'Meats'), ('Seafood', 'Seafood'), ('Condiments', 'Condiments'), ('Oils', 'Oils'), ('Seasoning', 'Seasoning'), ('Sauces', 'Sauces'), ('Legumes', 'Legumes'), ('Alcohol', 'Alcohol'), ('Soup', 'Soup'), ('Nuts', 'Nuts'), ('Dessert & Snack', 'Dessert & Snack'), ('Beverages', 'Beverages')], default='Fruits', max_length=100)),
            ],
        ),
    ]
