# Generated by Django 2.2.5 on 2019-09-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Appetizers', 'Appetizers'), ('Beverage', 'Beverage'), ('Soups', 'Soups'), ('Salads', 'Salads'), ('Main dishes', 'Main dishes'), ('Breads', 'Breads'), ('Rolls', 'Rolls'), ('Dessert', 'Dessert'), ('Misselaneous', 'Misselaneous')], default='Main dishes', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
